# Generated by Django 4.0 on 2022-02-04 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory'),
        ),
    ]
