# Generated by Django 3.2.12 on 2022-02-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220223_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtag',
            old_name='tag',
            new_name='name',
        ),
    ]
