# Generated by Django 3.2.12 on 2022-02-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_tag_blogtag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.RemoveField(
            model_name='blogtag',
            name='name',
        ),
        migrations.AddField(
            model_name='blogtag',
            name='name',
            field=models.ManyToManyField(blank=True, max_length=127, null=True, to='blog.Blog'),
        ),
    ]
