# Generated by Django 3.2.12 on 2022-02-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220223_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtag',
            name='tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(to='blog.BlogTag'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='name',
            field=models.TextField(blank=True, max_length=127, null=True),
        ),
    ]
