# Generated by Django 3.2.12 on 2022-03-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='desc_az',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='desc_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='title_az',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
