# Generated by Django 4.0 on 2022-02-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
