# Generated by Django 3.2.12 on 2022-03-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220319_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='products',
        ),
    ]
