# Generated by Django 3.2.12 on 2022-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_productcategory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
