# Generated by Django 3.2.12 on 2022-02-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20220221_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.BigIntegerField(blank=True, max_length=127, null=True),
        ),
    ]
