# Generated by Django 3.2.12 on 2022-02-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20220226_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('L', 'L'), ('S', 'S'), ('M', 'M'), ('XL', 'XL')], default='L', max_length=255),
        ),
    ]
