# Generated by Django 3.2.12 on 2022-03-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
