# Generated by Django 3.2.12 on 2022-03-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_checkout_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='state',
        ),
    ]
