# Generated by Django 3.2.12 on 2022-03-03 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_checkout_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
