# Generated by Django 4.0 on 2021-12-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leaders/')),
                ('name', models.CharField(max_length=127)),
                ('title', models.CharField(max_length=127)),
                ('social_media', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
