# Generated by Django 4.0 on 2021-12-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaders',
            options={'verbose_name': 'Leaders'},
        ),
    ]
