# Generated by Django 4.0 on 2021-12-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_leaders_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaders',
            options={'verbose_name': 'Leader'},
        ),
    ]
